name: ai_packages_for_flutter

packages:
  - packages/ai_agent_compose
  - packages/ai_packages_core
  - packages/ai_storage
  - packages/ai_ui
  - apps/**

scripts:
  analyze:
    exec: dart analyze .
  publish:
    exec: melos publish --no-dry-run
  codegen:
    exec: flutter pub run build_runner build --delete-conflicting-outputs && dart format --fix .