// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'enums.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `exec`

String dynamicPyCall({required PyCallObj pyCall}) =>
    RustLib.instance.api.crateApiPyCallDynamicPyCall(pyCall: pyCall);

/// example:
/// ```python
/// import json
/// def extract_json_obj(json_obj,name):
///     json_obj = json.loads(json_obj)
///     return str(json_obj[name])
/// ```
class PyCallObj {
  final ReturnType returnType;
  final String functionName;
  final String script;
  final List<String> args;

  const PyCallObj({
    required this.returnType,
    required this.functionName,
    required this.script,
    required this.args,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PyCallObj> newInstance(
          {required ReturnType returnType,
          required String functionName,
          required String script,
          required List<String> args}) =>
      RustLib.instance.api.crateApiPyCallPyCallObjNew(
          returnType: returnType,
          functionName: functionName,
          script: script,
          args: args);

  @override
  int get hashCode =>
      returnType.hashCode ^
      functionName.hashCode ^
      script.hashCode ^
      args.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PyCallObj &&
          runtimeType == other.runtimeType &&
          returnType == other.returnType &&
          functionName == other.functionName &&
          script == other.script &&
          args == other.args;
}
