[package]
name = "ai_dynamic_function_call"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tokio = "1"
deno_core = "=0.328.0"
flutter_rust_bridge = "=2.5.1"
pyo3 = { version = "=0.23.3", features = ["auto-initialize"] }

[dev-dependencies]
reqwest = "0.12.12"
